# Knowledge Graph Builder Configuration
# This file contains all configuration for running the knowledge graph builder

# General settings
general:
  builders: ["civic"]  # Added dgidb to the list
  output_dir: "/app/output"  # Output directory inside container
  convert_to_neptune: true
  
# Dataset configurations
datasets:
  enrichr:
    reactome:
      url: "https://maayanlab.cloud/Enrichr/geneSetLibrary?mode=text&libraryName=Reactome_2022"
      adapter: "ReactomeAdapter"
    
    wikipathway:
      url: "https://maayanlab.cloud/Enrichr/geneSetLibrary?mode=text&libraryName=WikiPathway_2023_Human"
      adapter: "WikiPathwayAdapter"
    
    biological_process:
      url: "https://maayanlab.cloud/Enrichr/geneSetLibrary?mode=text&libraryName=GO_Biological_Process_2023"
      adapter: "BiologicalProcessAdapter"
    
    molecular_function:
      url: "https://maayanlab.cloud/Enrichr/geneSetLibrary?mode=text&libraryName=GO_Molecular_Function_2023"
      adapter: "MolecularFunctionAdapter"
    
    cell_component:
      url: "https://maayanlab.cloud/Enrichr/geneSetLibrary?mode=text&libraryName=GO_Cellular_Component_2023"
      adapter: "CellComponentAdapter"
    
    # drug_targets:
    #   url: "https://maayanlab.cloud/Enrichr/geneSetLibrary?mode=text&libraryName=DGIdb_Drug_Targets_2024"
    #   adapter: "DrugDBAdapter"
  
  hpo:
    # HPO data files downloaded from URLs
    phenotype_hpoa:
      url: "http://purl.obolibrary.org/obo/hp/phenotype.hpoa"
      adapter: "PhenotypeHpoaAdapter"
      description: "Disease to phenotype associations"
    
    phenotype_to_genes:
      url: "http://purl.obolibrary.org/obo/hp/phenotype_to_genes.txt"
      adapter: "PhenotypeToGenesAdapter"
      description: "Phenotype to gene associations"
    
    genes_to_disease:
      url: "http://purl.obolibrary.org/obo/hp/genes_to_disease.txt"
      adapter: "GenesToDiseaseAdapter"
      description: "Gene to disease associations"

  civic:
    # CIViC data files downloaded from URLs
    features:
      url: "https://civicdb.org/downloads/01-Jul-2025/01-Jul-2025-FeatureSummaries.tsv"
      adapter: "CivicAdapter"
      description: "Gene/Feature summaries from CIViC"
    
    variants:
      url: "https://civicdb.org/downloads/01-Jul-2025/01-Jul-2025-VariantSummaries.tsv"
      adapter: "CivicAdapter"
      description: "Variant summaries from CIViC"
    
    variant_groups:
      url: "https://civicdb.org/downloads/01-Jul-2025/01-Jul-2025-VariantGroupSummaries.tsv"
      adapter: "CivicAdapter"
      description: "Variant group summaries from CIViC"
    
    molecular_profiles:
      url: "https://civicdb.org/downloads/01-Jul-2025/01-Jul-2025-MolecularProfileSummaries.tsv"
      adapter: "CivicAdapter"
      description: "Molecular profile summaries from CIViC"
    
    evidence:
      url: "https://civicdb.org/downloads/01-Jul-2025/01-Jul-2025-ClinicalEvidenceSummaries.tsv"
      adapter: "CivicAdapter"
      description: "Clinical evidence summaries from CIViC"
    
    assertions:
      url: "https://civicdb.org/downloads/01-Jul-2025/01-Jul-2025-AssertionSummaries.tsv"
      adapter: "CivicAdapter"
      description: "Clinical assertions from CIViC"

  dgidb:
    # DGIdb data files downloaded from URLs
    interactions:
      url: "https://dgidb.org/data/latest/interactions.tsv"
      adapter: "DgidbAdapter"
      description: "Drug-gene interactions from DGIdb"
    
    genes:
      url: "https://dgidb.org/data/latest/genes.tsv"
      adapter: "DgidbAdapter"
      description: "Gene entities from DGIdb"
    
    drugs:
      url: "https://dgidb.org/data/latest/drugs.tsv"
      adapter: "DgidbAdapter"
      description: "Drug entities from DGIdb"
    
    categories:
      url: "https://dgidb.org/data/latest/categories.tsv"
      adapter: "DgidbAdapter"
      description: "Gene categories from DGIdb"


# S3 configuration
s3:
  upload: true
  bucket: "genaixpubmend"  # Fixed: Add your actual S3 bucket name
  prefix: "enrichr-kg"    # Fixed: Add appropriate prefix

# Neptune configuration
neptune:
  load: true
  endpoint: "biocuration-knowledge-graph-instance-1.cdayu8m0iuvf.ap-southeast-1.neptune.amazonaws.com"
  iam_role_arn: "arn:aws:iam::009160053326:role/SSMCore"  # Fixed: Use role ARN, not policy ARN