# Knowledge Graph Builder Configuration
# This file contains all configuration for running the knowledge graph builder

# General settings
general:
  builders: ["hpo","enrichr"]  # Fixed: Use correct builder name
  output_dir: "/app/output"  # Output directory inside container
  convert_to_neptune: true
  
# Dataset configurations
datasets:
  enrichr:
    reactome:
      url: "https://maayanlab.cloud/Enrichr/geneSetLibrary?mode=text&libraryName=Reactome_2022"
      adapter: "ReactomeAdapter"
    
    wikipathway:
      url: "https://maayanlab.cloud/Enrichr/geneSetLibrary?mode=text&libraryName=WikiPathway_2023_Human"
      adapter: "WikiPathwayAdapter"
    
    biological_process:
      url: "https://maayanlab.cloud/Enrichr/geneSetLibrary?mode=text&libraryName=GO_Biological_Process_2023"
      adapter: "BiologicalProcessAdapter"
    
    molecular_function:
      url: "https://maayanlab.cloud/Enrichr/geneSetLibrary?mode=text&libraryName=GO_Molecular_Function_2023"
      adapter: "MolecularFunctionAdapter"
    
    cell_component:
      url: "https://maayanlab.cloud/Enrichr/geneSetLibrary?mode=text&libraryName=GO_Cellular_Component_2023"
      adapter: "CellComponentAdapter"
    
    drug_targets:
      url: "https://maayanlab.cloud/Enrichr/geneSetLibrary?mode=text&libraryName=DGIdb_Drug_Targets_2024"
      adapter: "DrugDBAdapter"
  hpo:
    # HPO data files downloaded from URLs
    phenotype_hpoa:
      url: "http://purl.obolibrary.org/obo/hp/phenotype.hpoa"
      adapter: "PhenotypeHpoaAdapter"
      description: "Disease to phenotype associations"
    
    phenotype_to_genes:
      url: "http://purl.obolibrary.org/obo/hp/phenotype_to_genes.txt"
      adapter: "PhenotypeToGenesAdapter"
      description: "Phenotype to gene associations"
    
    genes_to_disease:
      url: "http://purl.obolibrary.org/obo/hp/genes_to_disease.txt"
      adapter: "GenesToDiseaseAdapter"
      description: "Gene to disease associations"


# S3 configuration
s3:
  upload: true
  bucket: "genaixpubmend"  # Fixed: Add your actual S3 bucket name
  prefix: "enrichr-kg"    # Fixed: Add appropriate prefix

# Neptune configuration
neptune:
  load: true
  endpoint: "biocuration-knowledge-graph-instance-1.cdayu8m0iuvf.ap-southeast-1.neptune.amazonaws.com"
  iam_role_arn: "arn:aws:iam::009160053326:role/SSMCore"  # Fixed: Use role ARN, not policy ARN