# Knowledge Graph Builder Configuration
# Configuration for running both Enrichr and HPO builders

# General settings
general:
  builders: ["enrichr", "hpo"]  # List of builders to run
  output_dir: "/app/output"  # Output directory inside container
  convert_to_neptune: true
  
# Dataset configurations
datasets:
  enrichr:
    reactome:
      url: "https://maayanlab.cloud/Enrichr/geneSetLibrary?mode=text&libraryName=Reactome_2022"
      adapter: "ReactomeAdapter"
    
    wikipathway:
      url: "https://maayanlab.cloud/Enrichr/geneSetLibrary?mode=text&libraryName=WikiPathway_2023_Human"
      adapter: "WikiPathwayAdapter"
    
    biological_process:
      url: "https://maayanlab.cloud/Enrichr/geneSetLibrary?mode=text&libraryName=GO_Biological_Process_2023"
      adapter: "BiologicalProcessAdapter"
    
    molecular_function:
      url: "https://maayanlab.cloud/Enrichr/geneSetLibrary?mode=text&libraryName=GO_Molecular_Function_2023"
      adapter: "MolecularFunctionAdapter"
    
    cell_component:
      url: "https://maayanlab.cloud/Enrichr/geneSetLibrary?mode=text&libraryName=GO_Cellular_Component_2023"
      adapter: "CellComponentAdapter"
    
    drug_targets:
      url: "https://maayanlab.cloud/Enrichr/geneSetLibrary?mode=text&libraryName=DGIdb_Drug_Targets_2024"
      adapter: "DrugDBAdapter"

  hpo:
    # HPO data files are expected to be in the hpo/ directory
    # Configuration is handled by hpo_column_config.yaml
    phenotype_hpoa:
      file_path: "hpo/phenotype.hpoa"
      description: "Disease to phenotype associations"
    
    phenotype_to_genes:
      file_path: "hpo/phenotype_to_genes.txt"
      description: "Phenotype to gene associations"
    
    genes_to_disease:
      file_path: "hpo/genes_to_disease.txt"
      description: "Gene to disease associations"

# S3 configuration
s3:
  upload: false
  bucket: ""
  prefix: ""

# Neptune configuration
neptune:
  load: false
  endpoint: ""
  iam_role_arn: ""
