# Clinical Trials Configuration for RECENT STUDIES (2020+)
# More manageable dataset - studies updated since 2020

general:
  builders: ["clinicaltrials"]
  convert_to_neptune: true

clinical_trials:
  query_params:
    format: "json"
    query.term: "AREA[LastUpdatePostDate]RANGE[2020-01-01,MAX]"  # Studies updated since 2020
    pageSize: 1000
    
    # Optional additional filters
    # filter.overallStatus: ["RECRUITING", "NOT_YET_RECRUITING", "ACTIVE_NOT_RECRUITING", "COMPLETED"]
    
    # Optimize response size (comma-separated string, not list)
    fields: "NCTId,BriefTitle,OfficialTitle,OverallStatus,BriefSummary,StudyType,Phase,EnrollmentCount,Condition,InterventionName,LocationFacility,LocationCity,LocationCountry,LeadSponsorName"
  
  node_types:
    - "STUDY"
    - "SPONSOR"
    - "DRUG"
    - "DISEASE"
    - "LOCATION"
  
  node_fields:
    - "ID"
    - "BRIEF_TITLE"
    - "OFFICIAL_TITLE"
    - "STATUS"
    - "BRIEF_SUMMARY"
    - "TYPE"
    - "PHASES"
    - "NUMBER_OF_PATIENTS"
    - "SEX"
    - "MINIMUM_AGE"
    - "MAXIMUM_AGE"
  
  edge_types:
    - "STUDY_TO_DRUG"
    - "STUDY_TO_DISEASE"
    - "STUDY_TO_LOCATION"
    - "STUDY_TO_SPONSOR"

s3:
  upload: true
  bucket: "your-clinical-trials-bucket"
  prefix: "recent-studies-2020-plus"

neptune:
  load: false
  endpoint: "your-neptune-endpoint"
  iam_role_arn: "your-iam-role"
