# Knowledge Graph Builder Configuration
# Configuration for running HPO builder only

# General settings
general:
  builders: ["hpo"]  # List of builders to run
  output_dir: "/app/output"  # Output directory inside container
  convert_to_neptune: true
  
# Dataset configurations
datasets:
  hpo:
    # HPO data files are expected to be in the hpo/ directory
    # Configuration is handled by hpo_column_config.yaml
    phenotype_hpoa:
      file_path: "hpo/phenotype.hpoa"
      description: "Disease to phenotype associations"
    
    phenotype_to_genes:
      file_path: "hpo/phenotype_to_genes.txt"
      description: "Phenotype to gene associations"
    
    genes_to_disease:
      file_path: "hpo/genes_to_disease.txt"
      description: "Gene to disease associations"

# S3 configuration
s3:
  upload: false
  bucket: ""
  prefix: ""

# Neptune configuration
neptune:
  load: false
  endpoint: ""
  iam_role_arn: ""
