# BioCypher schema configuration for CIViC data
gene:
  represented_as: node
  label_in_input: gene
  preferred_id: id
  is_a: biolink:Gene
  properties:
    name:
      type: str
      description: Gene name
    aliases:
      type: list
      description: Alternative names for the gene
    description:
      type: str
      description: Description of the gene
    entrez_id:
      type: str
      description: Entrez Gene ID
    feature_type:
      type: str
      description: Type of feature
    data_source:
      type: str
      description: Source of the data

variant:
  represented_as: node
  label_in_input: variant
  preferred_id: id
  is_a: biolink:SequenceVariant
  properties:
    name:
      type: str
      description: Variant name
    feature_id:
      type: str
      description: ID of the associated feature (gene)
    feature_name:
      type: str
      description: Name of the associated feature (gene)
    feature_type:
      type: str
      description: Type of feature
    variant_types:
      type: str
      description: Type of variant
    aliases:
      type: list
      description: Alternative names for the variant
    gene:
      type: str
      description: Gene name
    entrez_id:
      type: str
      description: Entrez Gene ID
    chromosome:
      type: str
      description: Chromosome location
    start:
      type: str
      description: Start position
    stop:
      type: str
      description: Stop position
    reference_bases:
      type: str
      description: Reference bases
    variant_bases:
      type: str
      description: Variant bases
    data_source:
      type: str
      description: Source of the data

molecular_profile:
  represented_as: node
  label_in_input: molecular_profile
  preferred_id: id
  is_a: biolink:MolecularEntity
  properties:
    name:
      type: str
      description: Molecular profile name
    summary:
      type: str
      description: Summary of the molecular profile
    variant_ids:
      type: str
      description: Associated variant IDs
    evidence_score:
      type: str
      description: Evidence score
    aliases:
      type: list
      description: Alternative names for the molecular profile
    data_source:
      type: str
      description: Source of the data

evidence:
  represented_as: node
  label_in_input: evidence
  preferred_id: id
  is_a: biolink:EvidenceType
  properties:
    name:
      type: str
      description: Evidence name
    molecular_profile:
      type: str
      description: Associated molecular profile
    evidence_level:
      type: str
      description: Level of evidence (A, B, C, D, E)
    evidence_type:
      type: str
      description: Type of evidence
    evidence_direction:
      type: str
      description: Direction of evidence (supports, does not support)
    significance:
      type: str
      description: Clinical significance
    evidence_statement:
      type: str
      description: Evidence statement
    citation:
      type: str
      description: Citation information
    rating:
      type: str
      description: Evidence rating
    evidence_status:
      type: str
      description: Evidence status
    data_source:
      type: str
      description: Source of the data

assertion:
  represented_as: node
  label_in_input: assertion
  preferred_id: id
  is_a: biolink:Association
  properties:
    name:
      type: str
      description: Assertion name
    molecular_profile:
      type: str
      description: Associated molecular profile
    description:
      type: str
      description: Assertion description
    assertion_type:
      type: str
      description: Type of assertion
    assertion_direction:
      type: str
      description: Direction of assertion (supports, does not support)
    significance:
      type: str
      description: Clinical significance
    disease:
      type: str
      description: Associated disease
    doid:
      type: str
      description: Disease Ontology ID
    therapies:
      type: str
      description: Associated therapies
    summary:
      type: str
      description: Assertion summary
    amp_category:
      type: str
      description: AMP/ASCO/CAP category
    nccn_guideline:
      type: str
      description: NCCN guideline
    regulatory_approval:
      type: str
      description: Regulatory approval status
    fda_companion_test:
      type: str
      description: FDA companion test status
    evidence_item_ids:
      type: str
      description: Associated evidence item IDs
    data_source:
      type: str
      description: Source of the data

disease:
  represented_as: node
  label_in_input: disease
  preferred_id: id
  is_a: biolink:Disease
  properties:
    name:
      type: str
      description: Disease name
    doid:
      type: str
      description: Disease Ontology ID
    data_source:
      type: str
      description: Source of the data

therapy:
  represented_as: node
  label_in_input: therapy
  preferred_id: id
  is_a: biolink:Drug
  properties:
    name:
      type: str
      description: Therapy name
    data_source:
      type: str
      description: Source of the data

# Edge definitions
HAS_VARIANT:
  represented_as: edge
  label_in_input: HAS_VARIANT
  source: gene
  target: variant
  is_a: biolink:has_variant
  properties:
    data_source:
      type: str
      description: Source of the data

INCLUDES_VARIANT:
  represented_as: edge
  label_in_input: INCLUDES_VARIANT
  source: molecular_profile
  target: variant
  is_a: biolink:has_part
  properties:
    data_source:
      type: str
      description: Source of the data

HAS_EVIDENCE:
  represented_as: edge
  label_in_input: HAS_EVIDENCE
  source: molecular_profile
  target: evidence
  is_a: biolink:has_evidence
  properties:
    data_source:
      type: str
      description: Source of the data

HAS_ASSERTION:
  represented_as: edge
  label_in_input: HAS_ASSERTION
  source: molecular_profile
  target: assertion
  is_a: biolink:related_to
  properties:
    data_source:
      type: str
      description: Source of the data

SUPPORTS_ASSERTION:
  represented_as: edge
  label_in_input: SUPPORTS_ASSERTION
  source: evidence
  target: assertion
  is_a: biolink:supports
  properties:
    data_source:
      type: str
      description: Source of the data

ASSOCIATED_WITH_DISEASE:
  represented_as: edge
  label_in_input: ASSOCIATED_WITH_DISEASE
  source: evidence
  target: disease
  is_a: biolink:related_to
  properties:
    data_source:
      type: str
      description: Source of the data

TREATS_DISEASE:
  represented_as: edge
  label_in_input: TREATS_DISEASE
  source: therapy
  target: disease
  is_a: biolink:treats
  properties:
    data_source:
      type: str
      description: Source of the data

EVIDENCE_FOR_THERAPY:
  represented_as: edge
  label_in_input: EVIDENCE_FOR_THERAPY
  source: evidence
  target: therapy
  is_a: biolink:related_to
  properties:
    data_source:
      type: str
      description: Source of the data

ASSERTION_FOR_THERAPY:
  represented_as: edge
  label_in_input: ASSERTION_FOR_THERAPY
  source: assertion
  target: therapy
  is_a: biolink:related_to
  properties:
    data_source:
      type: str
      description: Source of the data

ASSERTION_FOR_DISEASE:
  represented_as: edge
  label_in_input: ASSERTION_FOR_DISEASE
  source: assertion
  target: disease
  is_a: biolink:related_to
  properties:
    data_source:
      type: str
      description: Source of the data
