# BioCypher schema configuration for CIViC data
gene:
  represented_as: node
  input_label: gene
  preferred_id: id
  is_a: biolink:Gene
  properties:
    entrez_id:
      type: str
      description: Entrez Gene ID
    civic_feature_id:
      type: str
      description: Associated CIViC feature ID
    data_source:
      type: str
      description: Source of the data

feature:
  represented_as: node
  input_label: feature
  preferred_id: id
  is_a: biolink:GenomicEntity
  properties:
    # Required columns
    feature_id:
      type: str
      description: CIViC feature ID
    feature_civic_url:
      type: str
      description: CIViC URL for the feature
    feature_type:
      type: str
      description: Type of feature (Gene, Fusion, etc.)
    name:
      type: str
      description: Feature name
    description:
      type: str
      description: Description of the feature
    # Additional metadata
    aliases:
      type: str
      description: Alternative names for the feature
    entrez_id:
      type: str
      description: Entrez Gene ID
    data_source:
      type: str
      description: Source of the data

fusion:
  represented_as: node
  input_label: fusion
  preferred_id: id
  is_a: biolink:GenomicEntity
  properties:
    data_source:
      type: str
      description: Source of the data
    civic_feature_id:
      type: str
      description: Associated CIViC feature ID

variant:
  represented_as: node
  input_label: variant
  preferred_id: id
  is_a: biolink:SequenceVariant
  properties:
    # Required 20 columns
    variant_id:
      type: str
      description: CIViC variant ID
    feature_type:
      type: str
      description: Type of genomic feature
    feature_id:
      type: str
      description: CIViC feature ID
    feature_name:
      type: str
      description: Name of the associated feature
    variant:
      type: str
      description: Variant name
    variant_aliases:
      type: str
      description: Alternative names for the variant
    variant_groups:
      type: str
      description: Variant group memberships
    variant_group_description:
      type: str
      description: Description of variant groups
    variant_types:
      type: str
      description: Type of variant
    gene:
      type: str
      description: Associated gene name
    chromosome:
      type: str
      description: Chromosome location
    start:
      type: str
      description: Start position
    stop:
      type: str
      description: Stop position
    reference_bases:
      type: str
      description: Reference bases
    variant_bases:
      type: str
      description: Variant bases
    representative_transcript:
      type: str
      description: Representative transcript
    ensembl_version:
      type: str
      description: Ensembl version
    reference_build:
      type: str
      description: Reference genome build
    hgvs_descriptions:
      type: str
      description: HGVS notation
    clinvar_ids:
      type: str
      description: ClinVar identifiers
    # Additional metadata
    name:
      type: str
      description: Variant name (duplicate of variant for compatibility)
    civic_url:
      type: str
      description: CIViC URL for the variant
    data_source:
      type: str
      description: Source of the data

MolecularProfile:
  represented_as: node
  input_label: molecular_profile
  preferred_id: id
  is_a: biolink:MolecularEntity
  properties:
    # Required columns
    name:
      type: str
      description: Molecular profile name
    molecular_profile_id:
      type: str
      description: CIViC molecular profile ID
    summary:
      type: str
      description: Summary of the molecular profile
    variant_ids:
      type: str
      description: Associated variant IDs
    variants_civic_url:
      type: str
      description: CIViC URLs for variants
    evidence_score:
      type: str
      description: Evidence score
    evidence_item_ids:
      type: str
      description: Associated evidence item IDs
    assertion_ids:
      type: str
      description: Associated assertion IDs
    aliases:
      type: str
      description: Alternative names for the molecular profile
    # Additional metadata
    data_source:
      type: str
      description: Source of the data

evidence:
  represented_as: node
  input_label: evidence
  preferred_id: id
  is_a: biolink:EvidenceType
  properties:
    # Required columns
    molecular_profile:
      type: str
      description: Associated molecular profile
    molecular_profile_id:
      type: str
      description: Associated molecular profile ID
    disease:
      type: str
      description: Associated disease
    doid:
      type: str
      description: Disease Ontology ID
    phenotypes:
      type: str
      description: Associated phenotypes
    therapies:
      type: str
      description: Associated therapies
    therapy_interaction_type:
      type: str
      description: Type of therapy interaction
    evidence_type:
      type: str
      description: Type of evidence
    evidence_direction:
      type: str
      description: Direction of evidence (supports, does not support)
    evidence_level:
      type: str
      description: Level of evidence (A, B, C, D, E)
    significance:
      type: str
      description: Clinical significance
    evidence_statement:
      type: str
      description: Evidence statement
    citation_id:
      type: str
      description: Citation ID
    source_type:
      type: str
      description: Type of source
    asco_abstract_id:
      type: str
      description: ASCO abstract ID
    citation:
      type: str
      description: Citation information
    nct_ids:
      type: str
      description: NCT IDs
    rating:
      type: str
      description: Evidence rating
    evidence_id:
      type: str
      description: CIViC evidence ID
    variant_origin:
      type: str
      description: Origin of variant
    evidence_civic_url:
      type: str
      description: CIViC URL for the evidence
    molecular_profile_civic_url:
      type: str
      description: CIViC URL for molecular profile
    # Additional metadata
    name:
      type: str
      description: Evidence name
    evidence_status:
      type: str
      description: Evidence status
    data_source:
      type: str
      description: Source of the data

assertion:
  represented_as: node
  input_label: assertion
  preferred_id: id
  is_a: biolink:Association
  properties:
    # Required columns
    assertion_direction:
      type: str
      description: Direction of assertion (supports, does not support)
    significance:
      type: str
      description: Clinical significance
    acmg_codes:
      type: str
      description: ACMG codes
    amp_category:
      type: str
      description: AMP/ASCO/CAP category
    nccn_guideline:
      type: str
      description: NCCN guideline
    regulatory_approval:
      type: str
      description: Regulatory approval status
    fda_companion_test:
      type: str
      description: FDA companion test status
    assertion_summary:
      type: str
      description: Assertion summary
    assertion_description:
      type: str
      description: Assertion description
    assertion_id:
      type: str
      description: CIViC assertion ID
    evidence_item_ids:
      type: str
      description: Associated evidence item IDs
    assertion_civic_url:
      type: str
      description: CIViC URL for the assertion
    # Existing columns
    name:
      type: str
      description: Assertion name
    molecular_profile_id:
      type: str
      description: Associated molecular profile ID
    molecular_profile:
      type: str
      description: Associated molecular profile
    disease:
      type: str
      description: Associated disease
    doid:
      type: str
      description: Disease Ontology ID
    therapies:
      type: str
      description: Associated therapies
    assertion_type:
      type: str
      description: Type of assertion
    data_source:
      type: str
      description: Source of the data

disease:
  represented_as: node
  input_label: disease
  preferred_id: id
  is_a: biolink:Disease
  properties:
    name:
      type: str
      description: Disease name
    doid:
      type: str
      description: Disease Ontology ID
    data_source:
      type: str
      description: Source of the data

therapy:
  represented_as: node
  input_label: therapy
  preferred_id: id
  is_a: biolink:Drug
  properties:
    name:
      type: str
      description: Therapy name
    data_source:
      type: str
      description: Source of the data

# Edge definitions
HasFeature:
  represented_as: edge
  input_label: HAS_FEATURE
  source: gene
  target: feature
  is_a: biolink:has_part
  properties:
    relationship_type:
      type: str
      description: Type of relationship
    data_source:
      type: str
      description: Source of the data

HasVariant:
  represented_as: edge
  input_label: HAS_VARIANT
  source: feature
  target: variant
  is_a: biolink:has_variant
  properties:
    data_source:
      type: str
      description: Source of the data

IncludesVariant:
  represented_as: edge
  input_label: INCLUDES_VARIANT
  source: molecular_profile
  target: variant
  is_a: biolink:has_part
  properties:
    data_source:
      type: str
      description: Source of the data

HasEvidence:
  represented_as: edge
  input_label: HAS_EVIDENCE
  source: molecular_profile
  target: evidence
  is_a: biolink:has_evidence
  properties:
    data_source:
      type: str
      description: Source of the data

SupportsAssertion:
  represented_as: edge
  input_label: SUPPORTS_ASSERTION
  source: evidence
  target: assertion
  is_a: biolink:supports
  properties:
    data_source:
      type: str
      description: Source of the data

AssociatedWithDisease:
  represented_as: edge
  input_label: ASSOCIATED_WITH_DISEASE
  source: evidence
  target: disease
  is_a: biolink:related_to
  properties:
    data_source:
      type: str
      description: Source of the data

EvidenceForTherapy:
  represented_as: edge
  input_label: EVIDENCE_FOR_THERAPY
  source: evidence
  target: therapy
  is_a: biolink:related_to
  properties:
    data_source:
      type: str
      description: Source of the data

AssertionForDisease:
  represented_as: edge
  input_label: ASSERTION_FOR_DISEASE
  source: assertion
  target: disease
  is_a: biolink:related_to
  properties:
    data_source:
      type: str
      description: Source of the data

AssertionForTherapy:
  represented_as: edge
  input_label: ASSERTION_FOR_THERAPY
  source: assertion
  target: therapy
  is_a: biolink:related_to
  properties:
    data_source:
      type: str
      description: Source of the data
