disease:
  input_label: disease
  properties:
    disease_name: str
  represented_as: node
disease to phenotypic feature association:
  input_label: disease to phenotypic feature association
  is_a: association
  properties:
    data_source: str
    evidence: str
    frequency: str
    onset: str
    reference: str
    sex: str
  represented_as: edge
  source: disease
  target: phenotypic feature
gene:
  input_label: gene
  properties: {}
  represented_as: node
gene to disease association:
  input_label: gene to disease association
  is_a: association
  properties:
    association_type: str
    data_source: str
    source: str
  represented_as: edge
  source: gene
  target: disease
gene to phenotypic feature association:
  input_label: gene to phenotypic feature association
  is_a: association
  properties:
    data_source: str
    via_disease: str
  represented_as: edge
  source: gene
  target: phenotypic feature
phenotypic feature:
  input_label: phenotypic feature
  properties:
    hpo_name: str
    ncbi_gene_id: str
  represented_as: node
phenotypic feature to disease association:
  input_label: phenotypic feature to disease association
  is_a: association
  properties:
    data_source: str
    via_gene: str
  represented_as: edge
  source: phenotypic feature
  target: disease
